### ISSUE TITLE
Currently broken

### ISSUE THREAD

**Issue by rohan-shah** [compomics/ms2pip_c#28]
We really want to use this, but there appear to be a very large number of bugs. For example:

- File ../models/HCD/pkl_B_4deep.c does not exist, should this be ../models/HCD/pkl_B_**9**deep.c?
- There is an else if without a beginning if in cython_modules/ms2pip_peaks_c.c, due to commenting?
- Functions score_B_zero, score_B_one, score_B_left, score_Y_one, score_Y_left are all undefined. 
- The install instructions don't work, as they are written.

**Comment by RalfG** [comment]
Hi!
Did you download the [latest release](https://github.com/compomics/ms2pip_c/releases/latest
), as written in the README.md? Because the most recent commit in the master branch indeed contains some bugs. I also recommend you to extract the precompiled files (see the `ms2pip_c_v20190130_precompiled_cython_modules.zip` on the releases page) into the `cython_modules` folder, as compiling them yourself can take a very long time. For this to work, you do need Python 3.7 (can be a conda env). 
Let me know if it works!
