### ISSUE TITLE
opt parameter in config file

### ISSUE THREAD

**Issue by MarcIsak** [compomics/ms2pip_c#60]
Hi, 

I'm taking a look at the config.txt file example in the repository here, and I noticed that all ptms have this opt parameter in between the mass shift and the AA residue regardless of whether they are fixed or variable like:

ptm=Oxidation,15.994915,opt,M
ptm=Carbamidomethyl,57.021464,opt,C

I just would like to know what opt really means in this case? Can this opt be changed in any way? 
In case of the Carbamidomethylation, I would like to add it as a fixed ptm, but have the oxidation on M as a variable modification. How can this be setup?

Best,

Marc

**Comment by RalfG** [comment]
Hi Marc,

We share this config file with some other projects, which is why this field is present. In the case of MS²PIP, the `opt`/`fix` field it is not taken into account. Each modification needs to be listed in the `modifications` column next to the peptide in the peprec input file. So fixed modifications also need to be listed explicitly for each peptide. There is an example in the [readme file](https://github.com/compomics/ms2pip_c#examples).

If you start from a fasta file (using fasta2speclib), there's another config file where you can set the fixed/variable modification input: https://github.com/compomics/ms2pip_c/wiki/fasta2speclib

**Comment by MarcIsak** [comment]
Thanks, I think I understand now!

Best,

Marc
